import { ICstNodeVisitor, RuleAddOperatorCstChildren, RuleAssignableValueCstChildren, RuleBooleanCstChildren, RuleDeclarationCstChildren, RuleFnAddExprCstChildren, RuleFnArgCstChildren, RuleFnAssignLOCstChildren, RuleFnAssignStatementCstChildren, RuleFnAtomicExprCstChildren, RuleFnBlockStatementCstChildren, RuleFnBodyCstChildren, RuleFnCallCstChildren, RuleFnConditionStatementCstChildren, RuleFnCstChildren, RuleFnExpressionCstChildren, RuleFnMacroConditionBranchCstChildren, RuleFnMacroConditionCstChildren, RuleFnMacroCstChildren, RuleFnMacroDefineCstChildren, RuleFnMacroIncludeCstChildren, RuleFnMultiplicationExprCstChildren, RuleFnParenthesisExprCstChildren, RuleFnRelationExprCstChildren, RuleFnReturnStatementCstChildren, RuleFnReturnTypeCstChildren, RuleFnStatementCstChildren, RuleFnVariableCstChildren, RuleFnVariableDeclarationCstChildren, RuleMultiplcationOperatorCstChildren, RuleNumberCstChildren, RulePropertyCstChildren, RulePropertyItemValueCstChildren, RuleProteryItemCstChildren, RuleRangeCstChildren, RuleRelationOperatorCstChildren, RuleRenderStateDeclarationCstChildren, RuleShaderCstChildren, RuleShaderPassCstChildren, RuleStatePropertyAssignCstChildren, RuleStructCstChildren, RuleSubShaderCstChildren, RuleTagAssignmentCstChildren, RuleTagCstChildren, RuleVariableTypeCstChildren, SubShaderPassPropertyAssignmentCstChildren, TupleFloat4CstChildren, TupleInt4CstChildren } from "./types";
import { ShaderParser } from "./parser";
import { AddOperatorAstNode, AstNode, BooleanAstNode, DeclarationAstNode, FnArgAstNode, FnAssignStatementAstNode, FnAstNode, FnAtomicExprAstNode, FnBlockStatementAstNode, FnBodyAstNode, FnCallAstNode, FnConditionStatementAstNode, FnMacroConditionAstNode, FnMacroConditionBranchAstNode, FnMacroDefineAstNode, FnMacroIncludeAstNode, FnReturnStatemtneAstNode, FnVariableAstNode, MultiplcationOperatorAstNode, NumberAstNode, PassPropertyAssignmentAstNode, PropertyAstNode, PropertyItemAstNode, RangeAstNode, RelationExprAstNode, RelationOperatorAstNode, RenderStateDeclarationAstNode, ReturnTypeAstNode, StatePropertyAssignAstNode, StructAstNode, TagAssignmentAstNode, TagAstNode, TupleNumber4AstNode, VariableDeclarationAstNode, VariableTypeAstNode } from "./astNode";
import { IPassAstContent, IShaderAstContent, ISubShaderAstContent } from "./astNode/types";
export {};
export declare const parser: ShaderParser;
declare const ShaderVisitorConstructor: new (...args: any[]) => import("chevrotain").ICstVisitor<any, AstNode<any>>;
export default class ShaderVisitor extends ShaderVisitorConstructor implements Partial<ICstNodeVisitor<any, AstNode>> {
    constructor();
    RuleShader(ctx: RuleShaderCstChildren): AstNode<IShaderAstContent>;
    RuleSubShader(ctx: RuleSubShaderCstChildren): AstNode<ISubShaderAstContent>;
    RuleShaderPass(ctx: RuleShaderPassCstChildren): AstNode<IPassAstContent>;
    RuleFnReturnType(children: RuleFnReturnTypeCstChildren, param?: any): ReturnTypeAstNode;
    RuleFn(ctx: RuleFnCstChildren): FnAstNode;
    RuleFnBody(ctx: RuleFnBodyCstChildren): FnBodyAstNode;
    RuleFnMacro(children: RuleFnMacroCstChildren, param?: any): any;
    RuleFnMacroDefine(children: RuleFnMacroDefineCstChildren, param?: any): FnMacroDefineAstNode;
    RuleFnMacroInclude(children: RuleFnMacroIncludeCstChildren, param?: any): FnMacroIncludeAstNode;
    RuleFnMacroCondition(children: RuleFnMacroConditionCstChildren, param?: any): FnMacroConditionAstNode;
    RuleFnMacroConditionBranch(children: RuleFnMacroConditionBranchCstChildren, param?: any): FnMacroConditionBranchAstNode;
    RuleFnStatement(ctx: RuleFnStatementCstChildren): any;
    RuleFnCall(ctx: RuleFnCallCstChildren): FnCallAstNode;
    RuleFnConditionStatement(ctx: RuleFnConditionStatementCstChildren): FnConditionStatementAstNode;
    RuleFnRelationExpr(ctx: RuleFnRelationExprCstChildren): RelationExprAstNode;
    RuleRelationOperator(children: RuleRelationOperatorCstChildren, param?: any): RelationOperatorAstNode;
    RuleFnBlockStatement(ctx: RuleFnBlockStatementCstChildren): FnBlockStatementAstNode;
    RuleFnAssignStatement(ctx: RuleFnAssignStatementCstChildren): FnAssignStatementAstNode;
    RuleFnExpression(ctx: RuleFnExpressionCstChildren): AstNode<any>;
    RuleAddOperator(children: RuleAddOperatorCstChildren, param?: any): AddOperatorAstNode;
    RuleFnAddExpr(ctx: RuleFnAddExprCstChildren): AstNode<any>;
    RuleMultiplcationOperator(children: RuleMultiplcationOperatorCstChildren, param?: any): MultiplcationOperatorAstNode;
    RuleFnMultiplicationExpr(ctx: RuleFnMultiplicationExprCstChildren): AstNode<any>;
    RuleFnAtomicExpr(ctx: RuleFnAtomicExprCstChildren): FnAtomicExprAstNode;
    RuleFnParenthesisExpr(ctx: RuleFnParenthesisExprCstChildren): AstNode<any>;
    RuleNumber(children: RuleNumberCstChildren): NumberAstNode;
    RuleBoolean(children: RuleBooleanCstChildren, param?: any): BooleanAstNode;
    RuleFnAssignLO(ctx: RuleFnAssignLOCstChildren): AstNode<any>;
    RuleFnVariable(ctx: RuleFnVariableCstChildren): FnVariableAstNode;
    RuleFnReturnStatement(ctx: RuleFnReturnStatementCstChildren): FnReturnStatemtneAstNode;
    RuleFnArg(ctx: RuleFnArgCstChildren): FnArgAstNode;
    RuleRenderStateDeclaration(ctx: RuleRenderStateDeclarationCstChildren): RenderStateDeclarationAstNode;
    RuleAssignableValue(children: RuleAssignableValueCstChildren, param?: any): AstNode<any>;
    RuleStatePropertyAssign(ctx: RuleStatePropertyAssignCstChildren): StatePropertyAssignAstNode;
    RuleFnVariableDeclaration(ctx: RuleFnVariableDeclarationCstChildren): VariableDeclarationAstNode;
    RuleStruct(ctx: RuleStructCstChildren): StructAstNode;
    RuleVariableType(children: RuleVariableTypeCstChildren, param?: any): VariableTypeAstNode;
    RuleDeclaration(ctx: RuleDeclarationCstChildren): DeclarationAstNode;
    SubShaderPassPropertyAssignment(ctx: SubShaderPassPropertyAssignmentCstChildren): PassPropertyAssignmentAstNode;
    RuleTag(ctx: RuleTagCstChildren): TagAstNode;
    RuleTagAssignment(ctx: RuleTagAssignmentCstChildren): TagAssignmentAstNode;
    RuleProperty(ctx: RulePropertyCstChildren): PropertyAstNode;
    RuleProteryItem(ctx: RuleProteryItemCstChildren): PropertyItemAstNode;
    RulePropertyItemValue(ctx: RulePropertyItemValueCstChildren): any;
    TupleFloat4(ctx: TupleFloat4CstChildren): TupleNumber4AstNode;
    TupleInt4(ctx: TupleInt4CstChildren): TupleNumber4AstNode;
    RuleRange(ctx: RuleRangeCstChildren): RangeAstNode;
}
